export const TODOS = {
  SET_TODOS: 'SET_TODOS',
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  MARK_COMPLETED: 'MARK_COMPLETED',
  SET_STATUS: 'SET_STATUS',
};
